@AuthenticationApi_HostAddress = http://localhost:5116

###

POST {{AuthenticationApi_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "Trudy",
  "email": "trdu@mail.com",
  "password": "trudypass",
  "role": "User"
}

###
POST {{AuthenticationApi_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "malthe",
  "password": "secret123"
}

###
GET {{AuthenticationApi_HostAddress}}/api/auth/auth-only
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFsdGhlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTE4MDk3NzIsImlzcyI6Ik15QXBwIiwiYXVkIjoiTXlBcHBVc2VycyJ9.wQsRtOvS9epFKdocRWbn_yPfyaYK5KGeOwJDOIwaUAypgkSALL7ciTzYvmh7SibPDWdqEm6MJffiXy1xqljjOg
Accept: application/json


###
GET {{AuthenticationApi_HostAddress}}/api/auth/admin-only
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWFsdGhlIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTE4MDk3NzIsImlzcyI6Ik15QXBwIiwiYXVkIjoiTXlBcHBVc2VycyJ9.wQsRtOvS9epFKdocRWbn_yPfyaYK5KGeOwJDOIwaUAypgkSALL7ciTzYvmh7SibPDWdqEm6MJffiXy1xqljjOg
Accept: application/json

###
GET {{AuthenticationApi_HostAddress}}/api/auth/users
Accept: application/json